# Generated by Django 3.2 on 2021-11-17 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Droits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('archive', models.BooleanField(default=False, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Droits',
                'verbose_name_plural': 'Droits',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='DroitsProfils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecriture', models.BooleanField(default=False, null=True)),
                ('lecture', models.BooleanField(default=False, null=True)),
                ('modification', models.BooleanField(default=False, null=True)),
                ('suppression', models.BooleanField(default=False, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('droit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conducteurs.droits')),
            ],
            options={
                'verbose_name': 'Droits profils',
                'verbose_name_plural': 'Droits profils',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_de_la_station', models.CharField(max_length=255, null=True)),
                ('responsable_de_la_station', models.CharField(max_length=255, null=True)),
                ('contact_de_la_station', models.CharField(max_length=255, null=True)),
                ('archive', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, null=True)),
                ('archive', models.BooleanField(default=False, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('droits', models.ManyToManyField(through='conducteurs.DroitsProfils', to='conducteurs.Droits')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profil',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='droitsprofils',
            name='profil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conducteurs.profils'),
        ),
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_et_prenom', models.TextField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('niveau_etude', models.CharField(choices=[('Secondaire sans diplôme', 'Secondaire sans diplôme'), ('Secondaire avec diplôme', 'Secondaire avec diplôme'), ('Primaire sans diplôme', 'Primaire sans diplôme'), ('Primaire avec diplôme', 'Primaire avec diplôme'), ('Lycée sans diplôme', 'Lycée sans diplôme'), ('Lycée avec diplôme', 'Lycée avec diplôme')], max_length=255, null=True)),
                ('telephone', models.CharField(max_length=255, null=True)),
                ('adresse', models.CharField(max_length=255, null=True)),
                ('immatriculation', models.TextField(null=True)),
                ('personne_a_prevenir', models.TextField(null=True)),
                ('photo_passeport', models.ImageField(blank=True, null=True, upload_to='photo_passeport')),
                ('numero_marie', models.CharField(max_length=20, null=True)),
                ('archive', models.BooleanField(default=False, null=True)),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conducteurs.station')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('pseudo', models.CharField(help_text="Le nom d'utilisateur servira à se connecter à la plateforme", max_length=255, null=True, unique=True)),
                ('nom', models.CharField(max_length=255, null=True)),
                ('prenom', models.CharField(max_length=255, null=True)),
                ('adresse', models.CharField(max_length=255, null=True)),
                ('telephone', models.BigIntegerField(null=True, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('sexe', models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=120, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('date_d_ajout', models.DateTimeField(auto_now_add=True, null=True, verbose_name="Date d'enrégistrement de l'utilisateur")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('profil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conducteurs.profils')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateur',
                'ordering': ('-id',),
            },
        ),
    ]
