# Generated by Django 3.2 on 2021-11-09 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conducteurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_de_la_station', models.CharField(max_length=255, null=True)),
                ('responsable_de_la_station', models.CharField(max_length=255, null=True)),
                ('contact_de_la_station', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.TextField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('niveau_etude', models.CharField(choices=[('Secondaire sans diplôme', 'Secondaire sans diplôme'), ('Secondaire avec diplôme', 'Secondaire avec diplôme'), ('Primaire sans diplôme', 'Primaire sans diplôme'), ('Primaire avec diplôme', 'Primaire avec diplôme'), ('Lycée sans diplôme', 'Lycée sans diplôme'), ('Lycée avec diplôme', 'Lycée avec diplôme')], max_length=255, null=True)),
                ('telephone', models.CharField(max_length=255, null=True)),
                ('adresse', models.CharField(max_length=255, null=True)),
                ('immatriculation', models.TextField(null=True)),
                ('personne_a_prevenir', models.TextField(null=True)),
                ('photo_passeport', models.ImageField(null=True, upload_to='photo_passeport')),
                ('numero_marie', models.CharField(max_length=20, null=True)),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conducteurs.station')),
            ],
        ),
    ]
