# Generated by Django 3.2 on 2021-11-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conducteurs', '0002_conducteur_station'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conducteur',
            old_name='nom_prenom',
            new_name='nom_et_prenom',
        ),
        migrations.AddField(
            model_name='conducteur',
            name='archive',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='archive',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
