# Generated by Django 3.2 on 2021-11-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conducteurs', '0003_auto_20211110_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conducteur',
            name='photo_passeport',
            field=models.ImageField(blank=True, null=True, upload_to='photo_passeport'),
        ),
    ]
